# Generated by Django 5.0.6 on 2024-07-05 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_marca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marca",
            name="nacionalidade",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="Modelo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("categoria", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="core.categoria")),
                ("marca", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="core.marca")),
            ],
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("ano", models.IntegerField(blank=True, default=0, null=True)),
                ("preco", models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ("acessorio", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="core.acessorio")),
                ("cor", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="core.cor")),
                ("modelo", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="core.modelo")),
            ],
        ),
    ]
